### ISSUE TITLE
Use template for both text and html

### ISSUE THREAD

**Issue by dagatsoin** [yanarp/nestjs-mailer#13]
Hi, 
thanks you for this module, it is very helpful.

**Context:**
I have an issue with my spam score which I can fix by sending both HTML and text version of the email.

** The issue:**
I have to "hardcode" the text version because the template field acts only for the HTML version.
```ts
this.mailerService.sendMail({
      from: `"Nekroz - Goblins Market" <${process.env.MAIL_USER ?? ""}>`,
      to: user.email, // list of receivers
      subject: "Goblins Market : bienvenue !", // Subject line
      template: "welcome", // The `.pug`, `.ejs` or `.hbs` extension is appended automatically.
      text: ejs.render(`Hello <%= locals.username %>. ...`,  { username: user.username }), // Template content duplication here
      context: {
        username: user.username,
      },
    });
```

Do you know a workaround for this ? I can help you with a PR if you provide me some guidelines to respect your module architecture.

**Comment by yanarp** [comment]
Hey @dagatsoin ,

As per your usage you want to use single option for both HTML and plain text to send content from your client to receiver's, it's seems to be non-negotiable at this moment, as both of these options serves a separate requirements for receiver side email client, which ensures to have both **plain text** and **template** for it's usage, 

check nodemailer documentation for reference -  http://nodemailer.com/extras/mailcomposer/#alternatives

If you happen to have any solution feel free to open a PR with separate service file for this implementation 👍 

Happy Hunting !

**Comment by dagatsoin** [comment]
Thx for the hint. I will come back if necessary :)
