### ISSUE TITLE
My template is not loaded

### ISSUE THREAD

**Issue by vladimirteddy** [yanarp/nestjs-mailer#37]
My config in app.module.ts:
` MailerModule.forRoot({
      transport: {
        host: 'smtp.gmail.com',
        port: 587,
        ignoreTLS: false,
        secure: false,
        auth: {
          user: process.env.GMAIL_USER,
          pass: process.env.GMAIL_PASS,
        },
      },
      defaults: {
        from: '"No Reply" <info@xxxxxxx>',
      },
      // preview: true,
      template: {
        dir: process.cwd() + '/src/templates/',
        adapter: new HandlebarsAdapter(),
        options: {
          strict: true,
        },
      },
    }),
`

My config in sendMail:
`
 const sendMail = await this._mailerService.sendMail({
        to: user.email,
        subject: "Confirm Your Email Address",
        context: {
name: 'my name'
        },
        template: 'my-template',
      });
`

My mail account receives mail but there is no template.
"@nestjs-modules/mailer": "^1.6.0"
"nodemailer": "^6.7.0"

**Comment by denizsult** [comment]
@vladimirteddy Hey! I'm facing the same problem as you. How did you solve it?
