### ISSUE TITLE
PugAdapter not available  for  '@nestjs-modules/mailer'

### ISSUE THREAD

**Issue by Emex4gman** [yanarp/nestjs-mailer#5]
I tried to use the  PugAdapter  from '@nestjs-modules/mailer',  

But I get this error 

Module '"../node_modules/@nestjs-modules/mailer"' has no exported member 'PugAdapter'.

**Comment by Emex4gman** [comment]
To use PugAdapter use

import { PugAdapter } from '@nestjs-modules/mailer/dist/adapters/pug.adapter';

https://nest-modules.github.io/mailer/docs/mailer.html

**Comment by matheus-vieira** [comment]
I tried to use the HandlebarsAdapter from '@nestjs-modules/mailer',

But I get this error

Module '"../node_modules/@nestjs-modules/mailer"' has no exported member 'HandlebarsAdapter'.

To resolve I used

import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';

Would be more cleaner to user some like, if possible:

import { HandlebarsAdapter } from '@nestjs-modules/mailer/adapter';

**Comment by Emex4gman** [comment]
> I tried to use the HandlebarsAdapter from '@nestjs-modules/mailer',
> 
> But I get this error
> 
> Module '"../node_modules/@nestjs-modules/mailer"' has no exported member 'HandlebarsAdapter'.
> 
> To resolve I used
> 
> import { HandlebarsAdapter } from '@nestjs-modules/mailer/dist/adapters/handlebars.adapter';
> 
> Would be more cleaner to user some like, if possible:
> 
> import { HandlebarsAdapter } from '@nestjs-modules/mailer/adapter';
> 
> or even, if the plugins is available
> 
> import { HandlebarsAdapter } from '@nestjs-modules/mailer';

Sadly you have to dive deeper to each adapter. But you right though. It would be cleaner to use that approach
